// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymowycfnhuowdghqxxlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltb3d5Y2ZuaHVvd2RnaHF4eGx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjE2NzEsImV4cCI6MjA2NjQzNzY3MX0.-Tim42bezYjWSV0cLuO3iwpK1UuBPhmXd90HPpmHQ7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);